name: cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: cicd-group-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci-smoke-test:
    runs-on: ubuntu-latest
    env:
      SOLARNETWORK_HOST: ${{ secrets.SOLARNETWORK_HOST }}
      SOLARNETWORK_TOKEN: ${{ secrets.SOLARNETWORK_TOKEN }}
      SOLARNETWORK_SECRET: ${{ secrets.SOLARNETWORK_SECRET }}
      SOLARNETWORK_TEST_NODE_ID: ${{ secrets.SOLARNETWORK_TEST_NODE_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: install dependencies
        run: uv sync --all-extras --dev

      - name: smoke test
        run: make ci-smoke-test
