name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: install dependencies
        run: uv sync --all-extras --dev

      - name: build package
        run: uv build

      - name: release
        run: uv publish --index pypi
